### PR TITLE
micropython on Beetle (Zephyr)

### PR DESCRIPTION
**Pull request by fvincenzo**
I completed the porting of micropython on Beetle via Zephyr and I found few minor issues that have been solved with my patch set below.

### CODE REVIEW

**Comment by pfalcon** [comment]
@fvincenzo : Thanks for the patches. I've cherry-picked "lib: Remove compilation warning" to master, but turned it broke other ports, so I had to redo it differently. Anyway, that issue is fixed now.

For other 2 changes, I'd prefer to squash them with earlier @daniel-thompson's patches, the motivation being is that I'd like to have Zephyr port be a "model" for new ports, and thus have a clean history. The drawback is that your authorship info will be lost. The changes are small, so I hope that's ok, but let me know if that's of concern to you.

4th change you just pushed looks good, will cherry pick to master next step.

Another note: I found that yesterday's change to zephyt master broke the build: https://gerrit.zephyrproject.org/r/#/c/5863/ . I pushed a stop-gap fix to this branch, while raising this issue and seeing if it can be fixed differently. Depending on the version of zephyr you use, you may need to revert that change locally ("zephyr/zephyr_getchar: Update for recent Zephyr refactor of console hooks.")

**Comment by pfalcon** [comment]
Ok, please rebase your branch.

**Comment by fvincenzo** [comment]
@pfalcon I do not have any problem to loose the authorship if you keep the signed-off information into the commit message.

**Comment by pfalcon** [comment]
Ok, these changes were squashed with Pin impl (sign-off's preserved), and pushed upstream as https://github.com/micropython/micropython/commit/67b6d9d499bee6283ae1005d0c829b8f552ac5af (please see it for more comments). Thanks!

**Pull request closed without merging**
