### PR TITLE
initialize variable 'o' with NULL in objtype.c to fix mpy-cross build

### PR DESCRIPTION
**Pull request by ernstnaezer**
I got this error on my mac when trying to make `mpy-cross`:

```
../py/objtype.c:1181:9: error: variable 'o' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
    if (MP_LIKELY(slots == NULL)) {
```

### CODE REVIEW

**Comment by pfalcon** [comment]
Thanks for giving my fork a try and for this report. But the code is written in such  a way that `o` can't be uninitialized in any case, and indeed, there's no errors when building it with gcc. I'm not against adding a workaround for another compiler, but first, I'd like to get more info about it. So, what compiler do you use on your mac? That's likely Clang, unless you made deliberate steps to use something else? Which version of Clang is that? Please also include the output of `clang -v`.

**Comment by pfalcon** [comment]
Ok, I was able to reproduce this with a recent version of clang: https://travis-ci.org/pfalcon/micropython/jobs/475061655

**Comment by ernstnaezer** [comment]
You're welcome! 

`clang -v` outputs the following:

```
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Glad you where able to reproduce this. Please let me know if there anything else I can test on my machine.

**Comment by pfalcon** [comment]
Thanks!

This issue should be fixed now, I fixed it a bit differently though and added explicit comment that it's due to Clang. The fix is squashed into ca90395bb9d669625bcfac50e1a05d8ed94742f9 . You would need to use `git pull --rebase` to update your repo.

**Comment by ernstnaezer** [comment]
nice. thanks

**Comment by pfalcon** [comment]
There were also issues with building ports/unix itself using Clang. Now everything fixed, and Clang build added to CI to catch any issues in the future. As of now, the build is green.

**Pull request closed without merging**
